name: build

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:

  source:
    name: Build source package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: docker://python
        with:
          args: 'sh -c "pip install build && python -m build --sdist"'

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*

  wheels:
    name: Build binary packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [aarch64]
        cibw_python: [ 'cp38-*', 'cp39-*', 'cp310-*' ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

        
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade cibuildwheel
      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_BUILD: ${{ matrix.cibw_python }}
      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [source, wheels]
    if: github.event_name == 'release'

    steps:
      - uses: actions/download-artifact@v2

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: artifact/
